////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;

namespace NosTale.Packets.Packets.ClientPackets
{
    [PacketHeader("exc_list")]
    public class ExcListPacket : PacketDefinition
    {
        #region Properties

        /// <summary>
        ///     Todo write a better way to handle that
        /// </summary>
        [PacketIndex(0, SerializeToEnd = true)]
        public string PacketData { get; set; }

        #endregion
    }
}