// <auto-generated />
namespace OpenNos.DAL.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class ClassType_In_Portal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ClassType_In_Portal));
        
        string IMigrationMetadata.Id
        {
            get { return "201911050637594_ClassType_In_Portal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
