namespace OpenNos.Domain
{
    public enum EventType
    {
        INSTANTBATTLE,
        LOD,
        MINILANDREFRESHEVENT,
        RANKINGREFRESH,
        ACT4SHIP,
        Act4Raid,
        TALENTARENA,
        CALIGOR,
        ICEBREAKER,
        AUTOREBOOT,
        ACT6RAID, 
        Act7Ship,
        XPRATE,
        RESETRATE,
        DROPRATE,
        FAIRYRATE,
        HERORATE,
        SHEEPGAME, 
        RAINBOWBATTLE,
        DAILYMISSIONEXTENSIONREFRESH,
        TOWERGAME,
        FAFNIRBOSS,
        YERTIRANDBOSS,
        GRASSLINBOSS,
        TOURNAMENT,
        METEORITEGAME,
        SHOPSHIP
    }
}