////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace NosTale.Packets.Packets.CommandPackets
{
    [PacketHeader("$AddPartner", PassNonParseablePacket = true, Authorities = new[] {AuthorityType.Administrator})]
    public class AddPartnerPacket : PacketDefinition
    {
        #region Methods

        public static string ReturnHelp() => "$AddPartner <VNum> <Level>";

        #endregion

        #region Properties

        [PacketIndex(0)] public short MonsterVNum { get; set; }

        [PacketIndex(1)] public byte Level { get; set; }

        #endregion
    }
}