////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using ChickenAPI.Enums;
using OpenNos.Core;
using OpenNos.Domain;

namespace NosTale.Packets.Packets.CommandPackets
{
    [PacketHeader("$AddShell", PassNonParseablePacket = true, Authorities = new[] {AuthorityType.Administrator})]
    public class AddShellEffectPacket : PacketDefinition
    {
        #region Methods

        public static string ReturnHelp() => "$AddShell <Slot> <EffectLevel> <Effect> <Value>";

        #endregion

        #region Properties

        [PacketIndex(0)] public byte Slot { get; set; }

        [PacketIndex(1)] public byte EffectLevel { get; set; }

        [PacketIndex(2)] public byte Effect { get; set; }

        [PacketIndex(3)] public short Value { get; set; }

        #endregion
    }
}