////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using ChickenAPI.Enums;
using OpenNos.Core;
using OpenNos.Domain;

namespace NosTale.Packets.Packets.CommandPackets
{
    [PacketHeader("$RollBack", PassNonParseablePacket = true, Authorities = new[] {AuthorityType.Administrator})]
    public class BackMobPacket : PacketDefinition
    {
        #region Properties

        public static string ReturnHelp() => "$RollBack";

        #endregion
    }
}