////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace NosTale.Packets.Packets.CommandPackets
{
    [PacketHeader("$Ban", PassNonParseablePacket = true, Authorities = new[] {AuthorityType.TGM})]
    public class BanPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)] public string CharacterName { get; set; }

        [PacketIndex(1)] public bool IsBanIp { get; set; }

        [PacketIndex(2)] public int Duration { get; set; }

        [PacketIndex(3, SerializeToEnd = true)]
        public string Reason { get; set; }

        public static string ReturnHelp() => "$Ban <IsBanIp> <Nickname> <Duration> <Reason>";

        #endregion
    }
}