////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using ChickenAPI.Enums;
using OpenNos.Core;
using OpenNos.Domain;

namespace NosTale.Packets.Packets.CommandPackets
{
    [PacketHeader("$Buff", PassNonParseablePacket = true, Authorities = new[] {AuthorityType.Administrator})]
    public class BuffPacket : PacketDefinition
    {
        #region Methods

        public static string ReturnHelp() => "$Buff <CardId> <?Level>";

        #endregion

        #region Properties

        [PacketIndex(0)] public short CardId { get; set; }

        [PacketIndex(1)] public byte? Level { get; set; }

        #endregion
    }
}