////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using ChickenAPI.Enums;
using OpenNos.Core;
using OpenNos.Domain;

namespace NosTale.Packets.Packets.CommandPackets
{
    [PacketHeader("$FLvl", PassNonParseablePacket = true, Authorities = new[] {AuthorityType.Administrator})]
    public class ChangeFairyLevelPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)] public short FairyLevel { get; set; }

        public static string ReturnHelp() => "$FLvl <Value>";

        #endregion
    }
}