////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using ChickenAPI.Enums;
using OpenNos.Core;
using OpenNos.Domain;

namespace NosTale.Packets.Packets.CommandPackets
{
    [PacketHeader("$ChangeClass", "$Class", PassNonParseablePacket = true,
        Authorities = new[] {AuthorityType.Administrator})]
    public class ChangeClassPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)] public ClassType ClassType { get; set; }

        public static string ReturnHelp() => "$ChangeClass | $Class <ClassType[0 = Adventurer, 1 = Swordsman, 2 = Archer, 3 = Mage, 4 = Martial Artist]>";

        #endregion
    }
}