////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using ChickenAPI.Enums;
using OpenNos.Core;
using OpenNos.Domain;

namespace NosTale.Packets.Packets.CommandPackets
{
    [PacketHeader("$CreateItem", "$item", PassNonParseablePacket = true, Authorities = new[] {AuthorityType.Administrator, AuthorityType.BetaTester })]
    public class CreateItemPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)] public short VNum { get; set; }

        [PacketIndex(1)] public short? Amount { get; set; }

        [PacketIndex(2)] public byte? Design { get; set; }

        [PacketIndex(3)] public byte? Upgrade { get; set; }

        public static string ReturnHelp() => "$CreateItem ITEMVNUM AMOUNT DESIGN/RARE/AMOUNT/WINGS UPDATE";

        #endregion
    }
}