////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using ChickenAPI.Enums;
using OpenNos.Core;
using OpenNos.Domain;

namespace NosTale.Packets.Packets.CommandPackets
{
    [PacketHeader("$FamilyFaction", PassNonParseablePacket = true, Authorities = new[] {AuthorityType.Administrator, AuthorityType.BetaTester })]
    public class FamilyFactionPacket : PacketDefinition
    {
        [PacketIndex(0)] public string FamilyName { get; set; }

        public static string ReturnHelp() => "$FamilyFaction <Name>";
    }
}