////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using ChickenAPI.Enums;
using OpenNos.Core;
using OpenNos.Domain;

namespace NosTale.Packets.Packets.CommandPackets
{
    [PacketHeader("$RemovePortal", PassNonParseablePacket = true, Authorities = new[] {AuthorityType.GM})]
    public class RemovePortalPacket : PacketDefinition
    {
        public static string ReturnHelp() => "$RemovePortal";
    }
}