////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using ChickenAPI.Enums;
using OpenNos.Core;
using OpenNos.Domain;

namespace NosTale.Packets.Packets.CommandPackets
{
    [PacketHeader("$ReputationRate", PassNonParseablePacket = true, Authorities = new[] {AuthorityType.Administrator})]
    public class ReputationRatePacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)] public int Value { get; set; }

        public static string ReturnHelp() => "$ReputationRate <Value>";

        #endregion
    }
}