////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using ChickenAPI.Enums;
using OpenNos.Core;
using OpenNos.Domain;

namespace NosTale.Packets.Packets.CommandPackets
{
    [PacketHeader("$ShutdownAll", PassNonParseablePacket = true, Authorities = new[] {AuthorityType.Administrator})]
    public class ShutdownAllPacket : PacketDefinition
    {
        [PacketIndex(0)] public string WorldGroup { get; set; }

        public static string ReturnHelp() => "$ShutdownAll <WorldGroup|*>";
    }
}