////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using ChickenAPI.Enums;
using OpenNos.Core;
using OpenNos.Domain;

namespace NosTale.Packets.Packets.CommandPackets
{
    [PacketHeader("$Sort", PassNonParseablePacket = true, Authorities = new[] {AuthorityType.Administrator})]
    public class SortPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)] public InventoryType? InventoryType { get; set; }

        public static string ReturnHelp() => "$Sort <InventoryType> -> 0 (equip) 1 (main) ...";

        #endregion
    }
}