////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace NosTale.Packets.Packets.CommandPackets
{
    [PacketHeader("$Stat", PassNonParseablePacket = true, Authorities = new[] {AuthorityType.Administrator})]
    public class StatCommandPacket : PacketDefinition
    {
        [PacketIndex(0)] public byte isStart { get; set; }

        public static string ReturnHelp() => "$Stat";
    }
}