////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using ChickenAPI.Enums;
using OpenNos.Core;
using OpenNos.Domain;

namespace NosTale.Packets.Packets.CommandPackets
{
    [PacketHeader("$Unmute", PassNonParseablePacket = true, Authorities = new[] {AuthorityType.DSGM, AuthorityType.Supporter})]
    public class UnmutePacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)] public string CharacterName { get; set; }

        public static string ReturnHelp() => "$Unmute <Nickname>";

        #endregion
    }
}